version: '3'
services:
  backend:
    image: wrench-turn/backend:latest
    container_name: wrench-turn_backend
    restart: unless-stopped 
    build: 
      context: . 
      dockerfile: backend.Dockerfile 
    volumes:
      - ./data:/app/data
      - ./.env.production:/app/.env.production
    ports:
     - 8080:8080

  frontend: 
    image: wrench-turn/frontend:latest 
    container_name: wrench-turn_frontend 
    restart: unless-stopped 
    build: 
      context: .
      dockerfile: frontend.Dockerfile 
    volumes: 
      - ./.env.production:/app/.env.production
    ports: 
      - 5173:80